Fix `AvatarAccount` type (#21671)
## **Description**

Fixes a type issue with `AvatarAccount`. Since it inherits props from
`AvatarBase` it expects `children`:
```
error TS2741: Property 'children' is missing in type '{ address: string; size: AvatarAccountSize.Xs; borderColor: BorderColor.transparent; }' but required in type 'AvatarAccountStyleUtilityProps'.
````

This PR fixes that!