fix: flaky test `Request-queue UI changes should show network specific to domain` (#33284)
<!--
Please submit this PR as a draft initially.
Do not mark it as "Ready for review" until the template has been
completely filled out, and PR status checks have passed at least once.
-->

## **Description**

The problem is a race condition due to dialog window management. We get
this error.;

```js
NoSuchWindowError: no such window: target window already closed
from unknown error: web view not found
```

Here is what happens:

1. We have a dialog open from one dapp
2. We click Cancel
3. We don't wait until the dialog is closed and switch to another dapp
4. We trigger a new tx
5. We switch to the dialog window -- which it's dialog with transaction
from step 1 (without the tx from the step4 yet)
6. Dialog is closed due to the step 2 action
7. We get error, window already closed


![Screenshot from 2025-05-29
19-47-45](https://github.com/user-attachments/assets/10d7c5b0-3110-46af-848a-dd4f5a962477)



[![Open in GitHub
Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/33284?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/33283

## **Manual testing steps**

1. Ci should work

## **Screenshots/Recordings**

<!-- If applicable, add screenshots and/or recordings to visualize the
before and after of your change. -->

### **Before**

<!-- [screenshots/recordings] -->

### **After**

<!-- [screenshots/recordings] -->

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor
Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask
Extension Coding
Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [x] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.