fix: flaky test `Import flow @no-mmi Import Account using json file` (#26240)
<!--
Please submit this PR as a draft initially.
Do not mark it as "Ready for review" until the template has been
completely filled out, and PR status checks have passed at least once.
-->

## **Description**

There is a race condition with the import account test, where we import
an account and then call the `locateAccountBalanceDOM`. The problem is
that this function will try to find the balance for the `account[0]` for
the ganache default accounts, which is `25 ETH`, however the newly
imported account has balance `0 ETH`. If the imported account flow is
fast, the element `25 ETH` won't be present when we try to find it,
making the test fail with the error:

```
TimeoutError: Waiting for element to be located By(xpath, .//*[./@data-testid = 'eth-overview__primary-currency'][(contains(string(.), '25 ETH') or contains(string(.), '25ETH'))])
```

The underlying problem is that we are looking for the wrong balance, as
the imported account has 0 ETH.
The fix is to modify the `locateAccountBalanceDOM` to be able to pass an
account as an optional argument, and then look for the balance for that
account if it's passed.


https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/94268/workflows/ef29c459-de15-4bc6-bef9-83b62611179d/jobs/3508512/parallel-runs/18

[![Open in GitHub
Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/26240?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/26241

## **Manual testing steps**

1. Check ci

## **Screenshots/Recordings**
See how in the failing artifact, we have the imported account with
balance 0, and it cannot locate the 25ETH element.


![image](https://github.com/user-attachments/assets/e60b9c01-eac8-445b-8c64-80b6fc3c0fc5)

See how if we add a delay, the test will always fails, as it looks for
25ETH which have already disappeared from the DOM.


https://github.com/user-attachments/assets/60294ed3-d760-4139-9fad-7080eb776dc3



## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor
Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask
Extension Coding
Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [x] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.

---------

Co-authored-by: Danica Shen <zhaodanica@gmail.com>