fix: audit failures `cipher-base` and `sha.js` (#35309)
<!--
Please submit this PR as a draft initially.
Do not mark it as "Ready for review" until the template has been
completely filled out, and PR status checks have passed at least once.
-->

## **Description**

This PR fixes the audit failures, with @Gudahtt 's awesome suggestion,
by running `yarn up -R [package]` :

```
Run yarn audit
├─ cipher-base
│  ├─ ID: 1106973
│  ├─ Issue: cipher-base is missing type checks, leading to hash rewind and passing on crafted data
│  ├─ URL: https://github.com/advisories/GHSA-cpq7-6gpm-g9rc
│  ├─ Severity: critical
│  ├─ Vulnerable Versions: <=1.0.4
│  │ 
│  ├─ Tree Versions
│  │  └─ 1.0.4
│  │ 
│  └─ Dependents
│     └─ create-hash@npm:1.2.0
│
└─ sha.js
   ├─ ID: 1106972
   ├─ Issue: sha.js is missing type checks leading to hash rewind and passing on crafted data
   ├─ URL: https://github.com/advisories/GHSA-95m3-7q98-8xr5
   ├─ Severity: critical
   ├─ Vulnerable Versions: <=2.4.11
   │ 
   ├─ Tree Versions
   │  └─ 2.4.11
   │ 
   └─ Dependents
      └─ @ngraveio/bc-ur@npm:1.1.13
Error: Process completed with exit code 1.

```



[![Open in GitHub
Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/35309?quickstart=1)

## **Changelog**

<!--
If this PR is not End-User-Facing and should not show up in the
CHANGELOG, you can choose to either:
1. Write `CHANGELOG entry: null`
2. Label with `no-changelog`

If this PR is End-User-Facing, please write a short User-Facing
description in the past tense like:
`CHANGELOG entry: Added a new tab for users to see their NFTs`
`CHANGELOG entry: Fixed a bug that was causing some NFTs to flicker`

(This helps the Release Engineer do their job more quickly and
accurately)
-->

CHANGELOG entry:

## **Related issues**

Fixes:

## **Manual testing steps**

1. Run `yarn audit`

## **Screenshots/Recordings**

<!-- If applicable, add screenshots and/or recordings to visualize the
before and after of your change. -->

### **Before**

<!-- [screenshots/recordings] -->

### **After**

<!-- [screenshots/recordings] -->

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor
Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask
Extension Coding
Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.