fix: flaky test `Swap should swap ETH to WETH` (#33628)
<!--
Please submit this PR as a draft initially.
Do not mark it as "Ready for review" until the template has been
completely filled out, and PR status checks have passed at least once.
-->

## **Description**
Sometimes the spec is flaky with this error, because there's a warning
that appears intermittently (sometimes appears and sometimes not).
There's already a bug ticket to fix this on the wallet side, and it was
attempted to fix on the test side, but without fixing all cases.
This PR mitigates this in a more robust way, and at the page object
class level.

```
TimeoutError: Waiting for element to be located By(xpath, //button[contains(text(), "Continue swapping")])
Wait timed out after 10103ms
    at /__w/metamask-extension/metamask-extension/node_modules/selenium-webdriver/lib/webdriver.js:929:22
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

```


[![Open in GitHub
Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/33628?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/33629

## **Manual testing steps**

1. All e2e should pass

## **Screenshots/Recordings**

<!-- If applicable, add screenshots and/or recordings to visualize the
before and after of your change. -->

### **Before**

<!-- [screenshots/recordings] -->

### **After**

<!-- [screenshots/recordings] -->

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor
Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask
Extension Coding
Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [x] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.