Fix error from missing `t` in dep array
```
SES_UNCAUGHT_EXCEPTION: TypeError: Cannot convert a Symbol value to a string
  at Array.join (<anonymous>)
  at Array.toString (<anonymous>)
  at Array.join (<anonymous>)
  at areHookInputsEqual (react-dom.development.js:14931:1)
  at updateMemo (react-dom.development.js:15861:1)
  at Object.useMemo (react-dom.development.js:16413:1)
  at useMemo (react.development.js:1532:1)
  at useBurnAddressAlert (useBurnAddressAlert.ts:38:17)
  at useTransactionAlerts (useConfirmationAlerts.ts:41:28)
  at useConfirmationAlerts (useConfirmationAlerts.ts:98:29)
  at useSetConfirmationAlerts (useSetConfirmationAlerts.ts:14:18)
  at ConfirmAlerts (confirm-alerts.tsx:13:3)
  at renderWithHooks (react-dom.development.js:14985:1)
  at updateFunctionComponent (react-dom.development.js:17356:1)
  at beginWork (react-dom.development.js:19063:1)
  at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
  at HTMLUnknownElement.sentryWrapped (sentry-install.js:22550:17)
  at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
  at invokeGuardedCallback (react-dom.development.js:4056:1)
  at beginWork$1 (react-dom.development.js:23964:1)
  at performUnitOfWork (react-dom.development.js:22779:1)
  at workLoopSync (react-dom.development.js:22707:1)
  at renderRootSync (react-dom.development.js:22670:1)
  at performSyncWorkOnRoot (react-dom.development.js:22293:1)
  at react-dom.development.js:11327:1
  at unstable_runWithPriority (scheduler.development.js:468:1)
  at runWithPriority$1 (react-dom.development.js:11276:1)
  at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
  at flushSyncCallbackQueue (react-dom.development.js:11309:1)
  at flushPassiveEffectsImpl (react-dom.development.js:23620:1)
  at unstable_runWithPriority (scheduler.development.js:468:1)
  at runWithPriority$1 (react-dom.development.js:11276:1)
  at flushPassiveEffects (react-dom.development.js:23447:1)
  at react-dom.development.js:23324:1
  at workLoop (scheduler.development.js:417:1)
  at flushWork (scheduler.development.js:390:1)
  at MessagePort.performWorkUntilDeadline (scheduler.development.js:157:1)
```