chore: Master-sync script updated  (#25004)
## **Description**
We observed that the master-sync script fails due to unmerged paths
(files with unresolved merge conflicts) in the working directory.
Therefore, this PR addresses the following failure that was identified.

```
harikajetpoluru@VWKGLFLX1 metamask-extension % yarn master-sync
Checked out branch: master-sync
Executed: git fetch
Executed: git reset --hard origin/master
Merge conflict encountered. Continuing script execution.
Error: Command failed: git restore --source origin/develop .
error: path 'ui/components/multichain/pages/send/components/content.tsx' is unmerged
error: path 'ui/pages/confirmations/components/confirm/blockaid-alert/blockaid-alert.tsx' is unmerged
```

[![Open in GitHub
Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/25004?quickstart=1)