fix: cp-12.20.1 Add missing hooks to `wallet_addEthereumChain` (#33821)
<!--
Please submit this PR as a draft initially.
Do not mark it as "Ready for review" until the template has been
completely filled out, and PR status checks have passed at least once.
-->

<!--
Write a short description of the changes included in this pull request,
also include relevant motivation and context. Have in mind the following
questions:
1. What is the reason for the change?
2. What is the improvement/solution?
-->

[![Open in GitHub
Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/33821?quickstart=1)

[Fixes bug reported by Uniswap in
slack](https://consensys.slack.com/archives/C017NBJL1S7/p1750281092438119?thread_ts=1738800121.354099&cid=C017NBJL1S7)

1. Go to https://chainlist.org/
2. open the console
3. Connect the wallet and attempt to add any network not already in the
network
4. You shouldn't see an RPC error:
```
{code: -32603, message: 'setTokenNetworkFilter is not a function', data: {…}}
```
<img width="694" alt="Screenshot 2025-06-20 at 4 33 57 PM"
src="https://github.com/user-attachments/assets/2f3b2f40-b303-4a21-9a8f-1772f3b0f4e7"
/>
5. Network should be added and switched to

<!-- If applicable, add screenshots and/or recordings to visualize the
before and after of your change. -->

https://github.com/user-attachments/assets/f3c8638b-fbcc-41e9-a485-0fa26ccab4c5

https://github.com/user-attachments/assets/b690bf29-e8bd-4246-bd5f-fac4ec4d68e1

- [ ] I've followed [MetaMask Contributor
Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask
Extension Coding
Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.

- [ ] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.